# Generated by Django 4.0.3 on 2022-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('image', models.CharField(max_length=250, verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие lte')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
            ],
        ),
    ]
